name: Deploy Blog
on:
  push:
    branches: [ main ]
  check_run:
    types: [rerequested, requested_action]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Runs a single command using the runners shell
      - name: deploy hexo
        run: |
          # twfb/blog 是部署博客的repo, 同时监测issue
          python3 deploy_issue.py "twfb/blog" ${{secrets.TOKEN}} > r
          if [[ -s r ]]; then
              git commit -m "$(cat r)" --allow-empty
              git push --set-upstream origin main
              while ! git push
              do
                  git pull
              done
          else
              npm run build
              npm run deploy
          fi
